"""Tests for commit analyzer."""

from datetime import datetime, timedelta
from unittest.mock import Mock

import pytest

from scanner.analyzer import CommitAnalyzer
from scanner.models import ObservationWindow


class TestCommitAnalyzer:
    """Tests for CommitAnalyzer class."""

    def test_get_active_contributors(self):
        """Test getting active contributors from commits."""
        # Mock repository
        repo = Mock()
        
        # Mock commits with different authors
        commit1 = Mock()
        commit1.author.login = "alice"
        commit2 = Mock()
        commit2.author.login = "bob"
        commit3 = Mock()
        commit3.author.login = "alice"  # Duplicate
        
        repo.get_commits.return_value = [commit1, commit2, commit3]
        
        # Create analyzer
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        # Get contributors
        contributors = analyzer.get_active_contributors()
        
        # Verify
        assert len(contributors) == 2
        assert "alice" in contributors
        assert "bob" in contributors
        repo.get_commits.assert_called_once_with(
            since=window.start_date,
            until=window.end_date
        )

    def test_get_active_contributors_with_none_author(self):
        """Test handling commits with no author."""
        repo = Mock()
        
        # Mock commits, one without author
        commit1 = Mock()
        commit1.author.login = "alice"
        commit2 = Mock()
        commit2.author = None
        
        repo.get_commits.return_value = [commit1, commit2]
        
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        contributors = analyzer.get_active_contributors()
        
        assert len(contributors) == 1
        assert "alice" in contributors

    def test_analyze_commits_basic(self):
        """Test basic commit analysis."""
        repo = Mock()
        
        # Mock commits
        commit1 = Mock()
        commit1.commit.message = "feat: add feature with AI assistance"
        commit1.author.login = "alice"
        
        commit2 = Mock()
        commit2.commit.message = "fix: resolve bug"
        commit2.author.login = "bob"
        
        repo.get_commits.return_value = [commit1, commit2]
        
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        result = analyzer.analyze_commits()
        
        assert result["total_commits"] == 2
        assert result["ai_assisted_commits"] == 1
        assert result["conventional_commits"] == 2  # Both commits are conventional format
        assert "alice" in result["contributors_with_ai"]

    def test_analyze_commits_with_ai_patterns(self):
        """Test detecting AI-assisted commits."""
        repo = Mock()
        
        # Mock commits with AI patterns
        commit1 = Mock()
        commit1.commit.message = "feat: code generated by Copilot"
        commit1.author.login = "alice"
        
        commit2 = Mock()
        commit2.commit.message = "Co-authored-by: GitHub Copilot"
        commit2.author.login = "bob"
        
        commit3 = Mock()
        commit3.commit.message = "refactor: normal commit"
        commit3.author.login = "charlie"
        
        repo.get_commits.return_value = [commit1, commit2, commit3]
        
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        result = analyzer.analyze_commits()
        
        assert result["total_commits"] == 3
        assert result["ai_assisted_commits"] == 2
        assert len(result["contributors_with_ai"]) == 2
        assert "alice" in result["contributors_with_ai"]
        assert "bob" in result["contributors_with_ai"]

    def test_analyze_commits_conventional_format(self):
        """Test detecting conventional commits."""
        repo = Mock()
        
        commit1 = Mock()
        commit1.commit.message = "feat: add new feature"
        commit1.author.login = "alice"
        
        commit2 = Mock()
        commit2.commit.message = "fix(auth): resolve login bug"
        commit2.author.login = "bob"
        
        commit3 = Mock()
        commit3.commit.message = "Update README"
        commit3.author.login = "charlie"
        
        repo.get_commits.return_value = [commit1, commit2, commit3]
        
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        result = analyzer.analyze_commits()
        
        assert result["total_commits"] == 3
        assert result["conventional_commits"] == 2

    def test_create_90day_window_default(self):
        """Test creating 90-day window with default end date."""
        window = CommitAnalyzer.create_90day_window()
        
        # Should end approximately now
        now = datetime.now()
        assert abs((window.end_date - now).total_seconds()) < 60  # Within 1 minute
        
        # Should start 90 days before end
        expected_start = window.end_date - timedelta(days=90)
        assert abs((window.start_date - expected_start).total_seconds()) < 1

    def test_create_90day_window_custom_end(self):
        """Test creating 90-day window with custom end date."""
        end_date = datetime(2026, 3, 1)
        window = CommitAnalyzer.create_90day_window(end_date)
        
        assert window.end_date == end_date
        expected_start = end_date - timedelta(days=90)
        assert window.start_date == expected_start

    def test_analyze_commits_error_handling(self):
        """Test that errors are handled gracefully."""
        repo = Mock()
        repo.get_commits.side_effect = Exception("API error")
        
        window = ObservationWindow(
            start_date=datetime(2025, 12, 1),
            end_date=datetime(2026, 3, 1)
        )
        analyzer = CommitAnalyzer(repo, window)
        
        # Should return empty result, not raise exception
        result = analyzer.analyze_commits()
        
        assert result["total_commits"] == 0
        assert result["ai_assisted_commits"] == 0
        assert result["conventional_commits"] == 0
        assert len(result["contributors_with_ai"]) == 0
